### ISSUE TITLE
internal/api tests do not build on main: authorADOEntraLane call in ado_names_e2e_test.go is missing its grade argument

### ISSUE THREAD

**Issue by cjohnstoniv** [cjohnstoniv/wardyn#771]
`go test ./internal/api/` does not build on `main` (27f23ffde), nor on any branch cut from it:

```
vet: internal/api/ado_names_e2e_test.go:87:97: not enough arguments in call to s.authorADOEntraLane
	have (context.Context, types.AgentRun, adoEntraRun, bool, dispatchLLMPlan, *types.RunPolicySpec, map[string]string, nil)
	want (context.Context, types.AgentRun, adoEntraRun, bool, adoEntraGrade, dispatchLLMPlan, *types.RunPolicySpec, map[string]string, []runner.InjectionGrant)
```

Two merges that each built on their own crossed:

- #503 (b60ee49be) added the `grade adoEntraGrade` parameter to `authorADOEntraLane` (`internal/api/runs_dispatch_ado_inject.go:435-437`).
- #496 (#485) added `internal/api/ado_names_e2e_test.go`, whose `TestADONames_AdmissionAndEntraLane` calls the old signature.

Every other test in the package is blocked behind the build failure, so any PR that touches `internal/api` cannot run its tests there until this is fixed.

**Fix.** Pass `adoEntraUngraded(), ` before `dispatchLLMPlan{` at `internal/api/ado_names_e2e_test.go:87`. With that one change, `go test -count=1 -p 4 ./internal/api/` exits 0 (the PG lane included), and `TestADONames_*` pass.

**Done when:** `go vet ./internal/api/` and `go test ./internal/api/` exit 0 on `main`.
